# Generated by Django 4.1.7 on 2023-08-04 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpApp', '0002_alter_employee_first_name_alter_employee_last_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
