# Generated by Django 4.1.7 on 2023-08-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpApp', '0003_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'The table storing employees information.'},
        ),
    ]
