# Generated by Django 4.1.7 on 2023-08-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpApp', '0005_employee_employee_last_na_acd780_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name="The employess's email address"),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='employee_email_c0d4f7_idx'),
        ),
    ]
