# Generated by Django 4.1.7 on 2023-08-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpApp', '0006_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name="Department's Name")),
                ('address', models.CharField(max_length=255, verbose_name='The address of this department')),
            ],
            options={
                'verbose_name': 'The table storing department information.',
                'db_table': 'department',
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='department_name_9f4150_idx'),
        ),
    ]
