# Generated by Django 4.1.7 on 2023-08-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpApp', '0007_department_department_department_name_9f4150_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EmpApp.department', verbose_name="The employess's department"),
        ),
    ]
