# Generated by Django 4.2.3 on 2023-08-04 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpApp', '0008_employee_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='EmpApp.department', verbose_name="The employess's department"),
        ),
    ]
